name: 🐞 Bug report
description: Report broken functionality.
labels: [bug]

body:
- type: markdown
  attributes:
    value: |
      🧐 **Guidelines:**

      - Search through [existing issues](https://github.com/Tyrrrz/LightBulb/issues?q=is%3Aissue) first to ensure that this bug has not been reported before.
      - Write a descriptive title for your issue. Avoid generic or vague titles such as "Something's not working" or "A couple of problems".
      - Keep your issue focused on one single problem. If you have multiple bug reports, please create separate issues for each of them.
      - Provide as much context as possible in the details section. Include screenshots, screen recordings, links, references, or anything else you may consider relevant.
      - If you want to ask a question instead of reporting a bug, please use [discussions](https://github.com/Tyrrrz/LightBulb/discussions/new) instead.

- type: input
  attributes:
    label: Version
    description: Which version of LightBulb does this bug affect?
    placeholder: ver X.Y.Z
  validations:
    required: true

- type: textarea
  attributes:
    label: Details
    description: Clear and thorough explanation of the bug. If relevant, include screenshots or screen recordings.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: Minimum steps required to reproduce the bug.
  validations:
    required: true